import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import AppSideBar from "./dashboard/app-sidebar";
import {
    SidebarProvider,
} from "@/components/ui/sidebar";
import { auth } from "@/auth";

export const metadata: Metadata = {
    title: "EventEase | Authorization",
    description: "Generated by create next app",
};

const ProtectedLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const session = await auth()
    return (<div>

        <SidebarProvider>
            <AppSideBar session={session?.user} />
            <div className="container mx-auto">
                {children}
            </div>
        </SidebarProvider>
    </div>
    );
}

export default ProtectedLayout